{
  "hash": "9609f53527988061bf950da16650283e",
  "result": {
    "markdown": "---\ntitle: \"14: Poisson Regression Models\"\nauthor: \"Derek Sollberger\"\ndate: \"2024-03-28\"\nexecute:\n  cache: true\n# format:\n#   revealjs:\n#     scrollable: true\nformat:\n  html:\n    toc: true\n---\n\n\n\\newcommand{\\ds}{\\displaystyle}\n\n# Poisson Regression Models\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n**Goal:** Explore Poisson and Negative Binomial Regression Models\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n## Data\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* source: [TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-12-03)\n* 2019-12-03 edition\n* [Open Data Philly](https://opendataphilly.org/datasets/parking-violations/)\n\n    * filtered to year 2017 data that had latitude/longitude\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-1_118671f7ae4ada261991f569f30d8adf'}\n\n```{.r .cell-code}\nlibrary(\"bayesrules\")\nlibrary(\"bayesplot\")\nlibrary(\"gt\")\nlibrary(\"patchwork\")\nlibrary(\"rstan\")\nlibrary(\"rstanarm\")\nlibrary(\"tidyverse\")\n\nknitr::opts_chunk$set(echo = TRUE)\n\n# tickets_raw <- readr::read_csv(\"https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-03/tickets.csv\")\n```\n:::\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-2_9d4fb9099be4d27fdc4bd9fd93995c27'}\n\n:::\n\n\n:::\n\n::::\n\n## Data Wrangling\n\n::::: {.panel-tabset}\n\n## Ideas\n\n* extract `month` and `day` from `datetime`\n* compute number of street sweeping violations per day\n* make categorical variable `weekend`\n\n## Code\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-3_26b264edb4501c3309f50225355ec831'}\n\n```{.r .cell-code}\ntickets_df <- tickets_raw |>\n  separate(issue_datetime, into = c(\"date\", \"time\"), sep = \" \") |>\n  separate(date, into = c(\"year\", \"month\", \"day\"), \n           sep = \"-\", remove = FALSE) |>\n  select(date, month, day, lat, lon) |>\n  group_by(month, day) |>\n  mutate(violations = n(), .before = date) |>\n  ungroup()\n\ntickets_df$day_of_week <- lubridate::wday(tickets_df$date, label = TRUE)\n\ntickets_df <- tickets_df |>\n  mutate(weekend = day_of_week %in% c(\"Sat\", \"Sun\")) |>\n  select(violations, month, day, weekend, lat, lon)\n\ntickets_df$month <- as.numeric(tickets_df$month)\ntickets_df$day <- as.numeric(tickets_df$day)\n\nset.seed(320)\ntickets_df_for_stan <- tickets_df |>\n  slice_sample(prop = 0.05)\n```\n:::\n\n\n:::::\n\n\n## Variables\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n### Response Variable\n\n$Y$: violations \n\n* *count variable*: number of street sweeping violations per day\n\n### Prediction\n\nHow many street sweeping violations will there be on March 28?\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"50%\"}\n### Predictor Variables\n\n* $X_{1}$: month (1, 2, 3, etc.)\n* $X_{2}$: day (of month)\n* $X_{3}$: weekend (boolean)\n* $X_{4}$: latitude\n* $X_{5}$: longitude\n:::\n\n::::\n\n# Recap: Normal Model\n\n::::: {.panel-tabset}\n\n## Model: Violations versus month and day\n\n$$Y = \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2}$$\n\n* $Y$: number of street sweeping violations per day\n* $X_{1}$: month (1, 2, 3, etc.)\n* $X_{2}$: day (of month)\n\n## Viz\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-4_c28dbb6018975cd23b654b8722426a81'}\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## Stan\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-5_f387d40ab1356245793bb01ed5d9c98a'}\n\n```{.r .cell-code}\nmod_normal <- stan_glm(violations ~ month + day,\n                       data = tickets_df_for_stan,\n                       family = gaussian,\n                       chains = 4, iter = 5000*2, \n                       refresh = 0, seed = 320)\n```\n:::\n\n\n## Diagnostics\n\n::: {.callout-note collapse=\"true\"}\n## Function\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-6_9d7eaf12da2b5973047d9991d8c5a125'}\n\n```{.r .cell-code}\nmodel_diagnostics <- function(the_stan_model){\n  p1 <- bayesplot::mcmc_trace(the_stan_model, size = 0.1) +\n  labs(title = \"MCMC Traces\")\n  print(p1)\n  \n  p2 <- bayesplot::mcmc_dens_overlay(the_stan_model) +\n  labs(title = \"Density Plots\")\n  print(p2)\n  \n  p3 <- bayesplot::mcmc_acf(the_stan_model) +\n  labs(title = \"Autocorrelations\")\n  print(p3)\n  \n  # effective sample size\n  print(\"Effective Sample Size:\")\n  print(bayesplot::neff_ratio(the_stan_model))\n  \n  # split-R metric\n  print(\"R-Hat\")\n  print(bayesplot::rhat(the_stan_model))\n}\n```\n:::\n\n\n:::\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-7_0f1ecb2fb5f683d5e0b470aef1f3c704'}\n\n```{.r .cell-code}\nmodel_diagnostics(mod_normal)\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Effective Sample Size:\"\n(Intercept)     month02     month03     month04     month05     month06 \n    0.06300     0.18470     0.19030     0.21290     0.19210     0.16740 \n    month07     month08     month09     month10     month11     month12 \n    0.17990     0.19480     0.22375     0.21370     0.22205     0.20810 \n      day02       day03       day04       day05       day06       day07 \n    0.07765     0.11980     0.08075     0.06810     0.07450     0.08970 \n      day08       day09       day10       day11       day12       day13 \n    0.09060     0.12655     0.08625     0.08960     0.06970     0.09080 \n      day14       day15       day16       day17       day18       day19 \n    0.07380     0.08285     0.08480     0.07525     0.10665     0.09255 \n      day20       day21       day22       day23       day24       day25 \n    0.08885     0.07235     0.12425     0.08060     0.07280     0.12020 \n      day26       day27       day28       day29       day30       day31 \n    0.07130     0.07865     0.07740     0.16275     0.08015     0.08770 \n      sigma \n    0.75945 \n[1] \"R-Hat\"\n(Intercept)     month02     month03     month04     month05     month06 \n  1.0014895   1.0011601   1.0012092   1.0007827   1.0010215   1.0008016 \n    month07     month08     month09     month10     month11     month12 \n  1.0008995   1.0010949   1.0005063   1.0008463   1.0006766   1.0011269 \n      day02       day03       day04       day05       day06       day07 \n  1.0012073   1.0007624   1.0010898   1.0012959   1.0010447   1.0008505 \n      day08       day09       day10       day11       day12       day13 \n  1.0010853   1.0005555   1.0009455   1.0009323   1.0011121   1.0007452 \n      day14       day15       day16       day17       day18       day19 \n  1.0013249   1.0011666   1.0012986   1.0011681   1.0008162   1.0007251 \n      day20       day21       day22       day23       day24       day25 \n  1.0006334   1.0014752   1.0005040   1.0010149   1.0011738   1.0007064 \n      day26       day27       day28       day29       day30       day31 \n  1.0013097   1.0010586   1.0011095   1.0003183   1.0009222   1.0010348 \n      sigma \n  0.9998761 \n```\n:::\n:::\n\n\n## PPC\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-8_209340b1355fc9a909e1bc89ff575167'}\n\n```{.r .cell-code}\nbayesplot::pp_check(mod_normal, nreps = 50) +\n  labs(title = \"Posterior Predictive Check\",\n       subtitle = \"Normal Regression, but should we allow for negative values?\",\n       caption = \"SML 320\")\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Model Stats\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-9_1df273b78465c4a0d6b885ca139fa668'}\n\n```{.r .cell-code}\nbroom.mixed::tidy(mod_normal,\n                  effects = c(\"fixed\", \"aux\"),\n                  conf.int = TRUE, conf.level = 0.90) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 44 × 5\n   term        estimate std.error conf.low conf.high\n   <chr>          <dbl>     <dbl>    <dbl>     <dbl>\n 1 (Intercept)    26.7       6.54   15.8       37.9 \n 2 month02        -2.22      4.41   -9.54       5.09\n 3 month03        -3.64      4.56  -11.1        3.90\n 4 month04         1.16      4.16   -5.66       8.05\n 5 month05        -2.86      4.29   -9.90       4.13\n 6 month06         2.74      4.22   -4.27       9.61\n 7 month07         7.68      4.06    1.02      14.3 \n 8 month08         7.01      4.47   -0.320     14.2 \n 9 month09        -2.62      5.09  -10.8        5.70\n10 month10         1.76      4.58   -5.80       9.29\n# ℹ 34 more rows\n```\n:::\n:::\n\n\n:::::\n\n# Poisson Model\n\n::::: {.panel-tabset}\n\n## Model: Violations versus month and day\n\n$$\\ln(\\lambda) = \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2}$$\n\n* $Y$: number of street sweeping violations per day\n* $X_{1}$: month (1, 2, 3, etc.)\n* $X_{2}$: day (of month)\n\n## Viz\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-10_1229340df8b1deccc976c22dacfbabe0'}\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Stan\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-11_fca189ae8867a7b184891fbb83784590'}\n\n```{.r .cell-code}\nmod_pois <- stan_glm(violations ~ month + day,\n                     data = tickets_df_for_stan,\n                     family = poisson, # changed here\n                     chains = 4, iter = 5000*2, \n                     refresh = 0, seed = 320)\n```\n:::\n\n\n## Diagnostics\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-12_be7acc580b77efba554574edc07d94fd'}\n\n```{.r .cell-code}\nmodel_diagnostics(mod_pois)\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Effective Sample Size:\"\n(Intercept)       month         day \n    0.99140     0.99975     0.94765 \n[1] \"R-Hat\"\n(Intercept)       month         day \n   1.000038    1.000006    0.999916 \n```\n:::\n:::\n\n\n## PPC\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-13_c5f6159d31927cc1a442f587b77ede22'}\n\n```{.r .cell-code}\nbayesplot::pp_check(mod_pois, nreps = 50) +\n  labs(title = \"Posterior Predictive Check\",\n       subtitle = \"Poisson Regression, nonnegative values\",\n       caption = \"SML 320\")\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n## Model Stats\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-14_26238c9725e74192e8a06d941e445ef0'}\n\n```{.r .cell-code}\nbroom.mixed::tidy(mod_pois,\n                  effects = c(\"fixed\", \"aux\"),\n                  conf.int = TRUE, conf.level = 0.90) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n  term        estimate std.error conf.low conf.high\n  <chr>          <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)   3.58      0.0233   3.54      3.62  \n2 month         0.0357    0.0027   0.0315    0.04  \n3 day          -0.0087    0.0009  -0.0102   -0.0071\n4 mean_PPD     39.4       0.467   38.7      40.2   \n```\n:::\n:::\n\n\n:::::\n\n\n# Poisson Regression\n\n## Poisson Data Model\n\n* count response variable $Y_{i}$ (per unit of time)\n* rate parameter $\\lambda_{i}$\n* likelihood\n\n$$Y_{i} | \\lambda_{i} \\sim \\text{Pois}(\\lambda_{i})$$\n\n## Expectation\n\nThe expected number $Y_{i}$ predicted by values $X_{ij}$ (over $j$ predictor variables) captured by parameter $\\lambda_{i}$ is\n\n$$\\text{E}(Y_{i} | \\lambda_{i}) = \\lambda_{i}$$\n\n## Log_Link Function\n\n$$Y_{i} | \\beta_{0}, \\beta_{1}, \\beta_{2} \\sim \\text{Pois}(\\lambda_{i}) \\quad\\text{with}\\quad \\ln(\\lambda_{i}) = \\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2}$$\n$$\\text{OR}$$\n$$Y_{i} | \\beta_{0}, \\beta_{1}, \\beta_{2} \\sim \\text{Pois}(\\lambda_{i}) \\quad\\text{with}\\quad \\lambda_{i} = e^{\\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2}}$$\n\n## Model Assumptions\n\n* **Structure of the data**: observed data are independent\n* **Structure of the response variable**: $Y$ has a Poisson structure that seeks a discrete *count* of events (per unit time)\n* **Structure of the relationship**: the *logged* average $Y$ can be written as a linear combination of the predictors\n\n$$\\lambda_{i} = e^{\\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2}}$$\n\n* **Structure of the variability in $Y$**:\n\n$$\\text{E}(Y) = \\text{Var}(Y) = \\lambda$$\n\neditor's note: [better visuals](https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html#introduction-to-poisson-regression) by Professors Roback and Legler at St Olaf College\n\n\n## Interpreting Coefficients\n\n### Intercept\n\nWhen $X_{1} = 0, X_{2} = 0, ...$\n\n$$\\text{E}(Y) = \\lambda = e^{\\beta_{0}} \\quad\\rightarrow\\quad \\beta_{0} = \\ln(\\lambda)$$\n\n* $\\beta_{0}$: logged average\n* $e^{\\beta_{0}}$: average value\n\n### Rates\n\nWhen we control other predictors and increase $X_{i}$ by one unit,\n\n$$\\beta_{i} = \\ln(\\lambda_{x+1}) - \\ln(\\lambda_{x}) \\quad\\rightarrow\\quad e^{\\beta_{i}} = \\ds\\frac{\\lambda_{x+1}}{\\lambda_{x}}$$\n\n* $\\beta_{i}$: change in logged average\n* $e^{\\beta_{i}}$: multiplicative change in average value\n\n# Poisson Model Usage\n\n## Coefficients\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-15_358ccc7a52b2dcd708b02d1af7acb55b'}\n\n```{.r .cell-code}\nbroom.mixed::tidy(mod_pois, effects = c(\"fixed\", \"aux\")) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  term        estimate std.error\n  <chr>          <dbl>     <dbl>\n1 (Intercept)   3.58      0.0233\n2 month         0.0357    0.0027\n3 day          -0.0087    0.0009\n4 mean_PPD     39.4       0.467 \n```\n:::\n:::\n\n\n$$e^{\\beta_{1}} = e^{0.0357} \\approx 1.0363$$\n\nAs we go from one month to the next, the number of street sweeping violations increases by about 3.6 percent.\n\n$$e^{\\beta_{2}} = e^{-0.0087} \\approx 0.9913$$\n\nAs we go from one day to the next, the number of street sweeping violations decreases by about 0.9 percent.\n\n## Prior Distributions\n\n::::: {.panel-tabset}\n\n## Code\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-16_c45476ede87d07f156348afa71700531'}\n\n```{.r .cell-code}\nrstanarm::prior_summary(mod_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPriors for model 'mod_pois' \n------\nIntercept (after predictors centered)\n ~ normal(location = 0, scale = 2.5)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = [0,0], scale = [2.5,2.5])\n  Adjusted prior:\n    ~ normal(location = [0,0], scale = [0.78,0.28])\n------\nSee help('prior_summary.stanreg') for more details\n```\n:::\n:::\n\n\n## Interpretation\n\nFor the prior distributions,\n\n$$e^{\\beta_{0}} \\in (e^{-5}, e^{5}) \\approx (0, 149)$$\n\n* the average number of street sweeping violations per day is in between zero and 149\n\n$$e^{\\beta_{1}} \\in (e^{-1.56}, e^{1.56}) \\approx (0.2101, 4.7588)$$\n\n* moving from one month to the next, the percent change in the number of street sweeping violations per day is in between 21 and 476 percent\n\n$$e^{\\beta_{2}} \\in (e^{-0.56}, e^{0.56}) \\approx (0.5712, 1.7507)$$\n\n* moving from one day to the next, the percent change in the number of street sweeping violations per day is in between -43 and 175 percent\n\n## Full Model\n\n$$\\begin{array}{rcl}\n  Y_{i}|\\beta_{0},\\beta_{1},\\beta_{2} & \\sim & \\text{Pois}(\\lambda_{i}) \\text{ with }\\ln(\\lambda_{i}) = \\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2} \\\\\n  \\beta_{0c} & \\sim & \\text{N}(0, 2.5^{2}) \\\\\n  \\beta_{1} & \\sim & \\text{N}(0, 0.78^{2}) \\\\\n  \\beta_{2} & \\sim & \\text{N}(0, 0.28^{2}) \\\\\n\\end{array}$$\n\n:::::\n\n\n\n\n\n## Posterior Prediction Interval\n\n::::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-17_2c3d9822bdc4dc4308dc3abe7136cbb6'}\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-18_30fd80eed7caaf1bd9433d49a88f6842'}\n\n```{.r .cell-code}\nthese_predictions <- rstanarm::posterior_predict(\n  mod_pois, newdata = data.frame(month = 3, day = 28))\ncredible_interval <- round(quantile(these_predictions, c(0.05, 0.95)))\nsubtitle_string <- paste0(\"90 Percent Credible Interval: (\",\n                          credible_interval[1], \", \",\n                          credible_interval[2], \")\")\nbayesplot::mcmc_areas(these_predictions, prob = 0.9) +\n  labs(title = \"Predictions for March 28\",\n       subtitle = subtitle_string,\n       caption = \"SML 320\",\n       x = \"number of street sweeping violations\")\n```\n:::\n\n\n:::::\n\n\n# Extended Model\n\n::::: {.panel-tabset}\n\n## Model\n\n$$\\ln(\\lambda) = \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{3} + \\beta_{4}X_{4}X_{5}$$\n\n* $Y$: number of street sweeping violations per day\n* $X_{1}$: month (1, 2, 3, etc.)\n* $X_{2}$: day (of month)\n* $X_{3}$: weekend (boolean)\n* $X_{4}X_{5}$: (possible interaction between) latitude and longitude\n\n## Stan\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-19_211b1de297919fca81fb64591ff9e86b'}\n\n```{.r .cell-code}\nmod_pois2 <- stan_glm(violations ~ month + day + weekend + lat:lon,\n                      data = tickets_df_for_stan,\n                      family = poisson,\n                      chains = 4, iter = 5000*2, \n                      refresh = 0, seed = 320)\n```\n:::\n\n\n## Diagnostics\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-20_f7ffd55b52d5795465b60b396cbf77c6'}\n\n```{.r .cell-code}\nmodel_diagnostics(mod_pois2)\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-20-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Effective Sample Size:\"\n(Intercept)       month         day weekendTRUE     lat:lon \n    1.05365     0.95060     0.98565     0.81800     1.05340 \n[1] \"R-Hat\"\n(Intercept)       month         day weekendTRUE     lat:lon \n  0.9999961   1.0001868   0.9999822   1.0001260   0.9999959 \n```\n:::\n:::\n\n\n## PPC\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-21_7ac9c95cb2c2f3fe72e1a3f82569e5ea'}\n\n```{.r .cell-code}\nbayesplot::pp_check(mod_pois2, nreps = 50) +\n  labs(title = \"Posterior Predictive Check\",\n       subtitle = \"Extended Poisson Regression Model\",\n       caption = \"SML 320\")\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n## Dispersion\n\n$$\\text{E}(Y) = \\text{Var}(Y)??$$\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-22_730ead954c0f4d0e757f5842a6b56da3'}\n\n```{.r .cell-code}\nmean(these_predictions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 31.43845\n```\n:::\n:::\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-23_a212099738cf1551c3f0f8d776be7ce3'}\n\n```{.r .cell-code}\nvar(these_predictions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1\n1 31.7904\n```\n:::\n:::\n\n\n\n:::::\n\n\n# Negative Binomial Regression\n\n## Motivation and Definition\n\n::: {.callout-note collapse=\"true\"}\n## Overdispersion\n\nA random variable $Y$ is **overdispersed** if the observed variability in $Y$ exceeds the variability *expected* by the assumed probability model of $Y$\n\n:::\n\nIf the count data appears to be demonstrating overdispersion, consider using the negative binomial distribution.\n\n::: {.callout-note collapse=\"true\"}\n## Negative Binomial model\n\nLet random variable $Y$ be some count, $Y\\in\\{0,1,2,…\\}$, that can be modeled by the Negative Binomial with **mean parameter** $\\mu$ and **reciprocal dispersion parameter** $r$:\n\n$$Y|\\mu,r \\sim \\text{NegBin}(\\mu,r)$$\n\nThen $Y$ has conditional pmf\n\n$$f(y|\\mu,r) = \\binom{y+r-1}{r}\\left( \\ds\\frac{r}{\\mu+r} \\right)^{r}\\left(  \\ds\\frac{\\mu}{\\mu+r}\\right)^{y} \\text{ for } y\\in\\{0,1,2,...\\}$$\n\nwith statistics\n\n$$\\text{E}(Y|\\mu,r) = \\mu \\quad\\text{and}\\quad \\text{Var}(Y|\\mu,r) = \\mu + \\ds\\frac{\\mu^{2}}{r}$$\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Commentary\n\n* for large $r$, this distribution behaves like the Poisson distribution\n* for small $r$,  and $Y$ is overdispersed\n* $\\text{Var}(Y) \\neq \\text{E}(Y)$\n\n:::\n\n\n# Negative Binomial Model\n\n::::: {.panel-tabset}\n\n## Model\n\n$$\\ln(\\mu) = \\beta_{0} + \\beta_{1}X_{1} + \\beta_{2}X_{2} + \\beta_{3}X_{3} + \\beta_{4}X_{4}X_{5}$$\n\n* $Y$: number of street sweeping violations per day\n* $X_{1}$: month (1, 2, 3, etc.)\n* $X_{2}$: day (of month)\n* $X_{3}$: weekend (boolean)\n* $X_{4}X_{5}$: (possible interaction between) latitude and longitude\n\n## Stan\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-24_518de3cd5f0e056e4843d14a7b528962'}\n\n```{.r .cell-code}\nmod_neg_bin <- stan_glm(violations ~ month + day + weekend + lat:lon,\n                      data = tickets_df_for_stan,\n                      family = neg_binomial_2, #changed here\n                      chains = 4, iter = 5000*2, \n                      refresh = 0, seed = 320)\n```\n:::\n\n\n## Diagnostics\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-25_d60f90b26fcf42af3bbd575b7b72efcb'}\n\n```{.r .cell-code}\nmodel_diagnostics(mod_neg_bin)\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-25-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Effective Sample Size:\"\n          (Intercept)                 month                   day \n              1.46255               1.27635               1.47720 \n          weekendTRUE               lat:lon reciprocal_dispersion \n              1.33420               1.46210               1.47700 \n[1] \"R-Hat\"\n          (Intercept)                 month                   day \n            0.9998795             0.9999110             0.9998873 \n          weekendTRUE               lat:lon reciprocal_dispersion \n            0.9999143             0.9998797             0.9998440 \n```\n:::\n:::\n\n\n:::::\n\n## Prior Distributions\n\n::::: {.panel-tabset}\n\n## Code\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-26_4fc5eb0150d15a30a4889f752eb619c4'}\n\n```{.r .cell-code}\nmodel_priors <- rstanarm::prior_summary(mod_neg_bin)\nmodel_priors #print\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPriors for model 'mod_neg_bin' \n------\nIntercept (after predictors centered)\n ~ normal(location = 0, scale = 2.5)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = [0,0,0,...], scale = [2.5,2.5,2.5,...])\n  Adjusted prior:\n    ~ normal(location = [0,0,0,...], scale = [ 0.78, 0.28,19.58,...])\n\nAuxiliary (reciprocal_dispersion)\n ~ exponential(rate = 1)\n------\nSee help('prior_summary.stanreg') for more details\n```\n:::\n\n```{.r .cell-code}\n# model_priors$prior$adjusted_scale #after autoscaling\n```\n:::\n\n\n## Interpretation\n\nFor the prior distributions,\n\n$$e^{\\beta_{0}} \\in (e^{-5}, e^{5}) \\approx (0, 149)$$\n\n* the average number of street sweeping violations per day is in between zero and 149\n\n$$e^{\\beta_{1}} \\in (e^{-1.56}, e^{1.56}) \\approx (0.2101, 4.7588)$$\n\n* moving from one month to the next, the percent change in the number of street sweeping violations per day is in between 21 and 476 percent\n\n$$e^{\\beta_{2}} \\in (e^{-0.56}, e^{0.56}) \\approx (0.5712, 1.7507)$$\n\n* moving from one day to the next, the percent change in the number of street sweeping violations per day is in between -43 and 175 percent\n\n$$e^{\\beta_{3}} \\in (e^{-39.16}, e^{39.16})$$\n\n* [We have a vague prior for the coefficient of the categorical variable]\n\n\n## Full Model\n\n$$\\begin{array}{rcl}\n  Y_{i}|\\beta_{0},\\beta_{1},\\beta_{2} & \\sim & \\text{NegBin}(\\mu_{i},r) \\text{ with }\\ln(\\mu_{i}) = \\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2} + ... \\\\\n  \\beta_{0c} & \\sim & \\text{N}(0, 2.5^{2}) \\\\\n  \\beta_{1} & \\sim & \\text{N}(0, 0.78^{2}) \\\\\n  \\beta_{2} & \\sim & \\text{N}(0, 0.28^{2}) \\\\\n  \\beta_{3} & \\sim & \\text{N}(0, 19.58^{2}) \\\\\n  \\beta_{4} & \\sim & \\text{N}(0, 1.09^{2}) \\\\\n  r & \\sim & \\text{Exp}(1) \\\\\n\\end{array}$$\n\n:::::\n\n## PPC\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-27_bd21d61f2c04283d1c804842f8321a78'}\n\n```{.r .cell-code}\nbayesplot::pp_check(mod_neg_bin, nreps = 50) +\n  labs(title = \"Posterior Predictive Check\",\n       subtitle = \"Negative Binomial Regression Model\",\n       caption = \"SML 320\")\n```\n\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Coefficients\n\nLike in the Poisson regression models, the coefficents of negative binomial regression models are also desribed with the logarithmic transformation in mind.\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-28_af6153999b521203d9c12a9978181b30'}\n\n```{.r .cell-code}\nbroom.mixed::tidy(mod_neg_bin, effects = c(\"fixed\", \"aux\"),\n                  conf.int = TRUE, conf.level = 0.90) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  term        estimate std.error conf.low conf.high\n  <chr>          <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept) 124.       24.9     82.2     165.    \n2 month         0.022     0.0066   0.0112    0.0329\n3 day          -0.0039    0.0023  -0.0077   -0.0002\n4 weekendTRUE   0.879     0.160    0.627     1.15  \n5 lat:lon       0.04      0.0083   0.0262    0.0536\n6 mean_PPD     39.5       1.16    37.6      41.4   \n```\n:::\n:::\n\n\n$$e^{\\beta_{1}} = e^{0.0220} \\approx 1.0222$$\n\n* As we go from one month to the next, the number of street sweeping violations increases by about 2.2 percent.\n\n$$e^{\\beta_{2}} = e^{-0.0039} \\approx 0.9961$$\n\n* As we go from one day to the next, the number of street sweeping violations decreases by about 0.04 percent.\n\n$$e^{\\beta_{3}} = e^{0.8791} \\approx 2.4087$$\n\n* Compared to a weekday, the expected amount of street sweeping violations on a weekend day is 241 percent higher (caution: sample size issue).\n\n$$1.0 \\notin (e^{0.0262}, e^{0.0536})$$\n\n* We may have some evidence that $\\beta_{4} > 1.0$, or the notion that there may be an interaction effect between latitude and longitude\n\n## Posterior Prediction Interval\n\n::::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-29_d342b3d0f12a4d8357c7ddd94bf2a142'}\n::: {.cell-output-display}\n![](14_poisson_neg_binomial_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-30_c3740ffffa74013361ee4af96ce41970'}\n\n```{.r .cell-code}\nthese_predictions <- rstanarm::posterior_predict(\n  mod_neg_bin, newdata = data.frame(month = 3, \n                                    day = 28,\n                                    weekend = FALSE,\n                                    lat = mean(tickets_df$lat),\n                                    lon = mean(tickets_df$lon)))\ncredible_interval <- round(quantile(these_predictions, c(0.05, 0.95)))\nsubtitle_string <- paste0(\"90 Percent Credible Interval: (\",\n                          credible_interval[1], \", \",\n                          credible_interval[2], \")\")\nbayesplot::mcmc_areas(these_predictions, prob = 0.9) +\n  labs(title = \"Predictions for March 28\",\n       subtitle = subtitle_string,\n       caption = \"SML 320\",\n       x = \"number of street sweeping violations\")\n```\n:::\n\n\n:::::\n\n## Dispersion\n\n$$\\text{E}(Y) = \\text{Var}(Y)??$$\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-31_61d690e8bdb82c3defdf7be62fe2b6a9'}\n\n```{.r .cell-code}\nmean(these_predictions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 33.85635\n```\n:::\n:::\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-32_73695efa748c3e100a6758b7cbd926c5'}\n\n```{.r .cell-code}\nvar(these_predictions)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         1\n1 175.5899\n```\n:::\n:::\n\n\n\n# Summary\n\n* If response $Y$ is nonnegative count data, consider Poisson regression models\n* If data is overdispersed, consider negative binomial regression models\n* In these cases, carefully describe coefficients after the logarithmic transformation\n\n\n# Footnotes\n\n* [Poisson Regression](https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html#introduction-to-poisson-regression) by Professors Roback and Legler at St Olaf College\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell hash='14_poisson_neg_binomial_cache/html/unnamed-chunk-33_1a5fe7e933a90a21e48427cd4668bd9d'}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.3.2 (2023-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1      dplyr_1.1.4       \n [5] purrr_1.0.2        readr_2.1.5        tidyr_1.3.1        tibble_3.2.1      \n [9] ggplot2_3.4.3      tidyverse_2.0.0    rstanarm_2.21.4    Rcpp_1.0.11       \n[13] rstan_2.32.5       StanHeaders_2.32.5 patchwork_1.1.2    gt_0.9.0          \n[17] bayesplot_1.10.0   bayesrules_0.0.2  \n\nloaded via a namespace (and not attached):\n [1] gridExtra_2.3      inline_0.3.19      rlang_1.1.1        magrittr_2.0.3    \n [5] snakecase_0.11.0   matrixStats_1.0.0  e1071_1.7-13       compiler_4.3.2    \n [9] loo_2.6.0          callr_3.7.3        vctrs_0.6.5        reshape2_1.4.4    \n[13] pkgconfig_2.0.3    crayon_1.5.2       fastmap_1.1.1      ellipsis_0.3.2    \n[17] labeling_0.4.3     utf8_1.2.4         threejs_0.3.3      promises_1.2.1    \n[21] rmarkdown_2.24     tzdb_0.4.0         markdown_1.8       ps_1.7.5          \n[25] nloptr_2.0.3       xfun_0.40          jsonlite_1.8.7     later_1.3.1       \n[29] parallel_4.3.2     prettyunits_1.2.0  R6_2.5.1           dygraphs_1.1.1.6  \n[33] stringi_1.8.3      boot_1.3-28.1      knitr_1.43         zoo_1.8-12        \n[37] base64enc_0.1-3    httpuv_1.6.11      Matrix_1.6-1.1     splines_4.3.2     \n[41] igraph_1.4.3       timechange_0.3.0   tidyselect_1.2.0   rstudioapi_0.15.0 \n[45] yaml_2.3.8         codetools_0.2-19   miniUI_0.1.1.1     curl_5.0.2        \n[49] processx_3.8.1     pkgbuild_1.4.0     lattice_0.21-9     plyr_1.8.8        \n[53] withr_3.0.0        shiny_1.7.5        groupdata2_2.0.2   evaluate_0.21     \n[57] survival_3.5-7     proxy_0.4-27       RcppParallel_5.1.7 xts_0.13.1        \n[61] xml2_1.3.6         pillar_1.9.0       DT_0.28            stats4_4.3.2      \n[65] shinyjs_2.1.0      generics_0.1.3     hms_1.1.3          rstantools_2.3.1  \n[69] munsell_0.5.0      scales_1.2.1       minqa_1.2.5        gtools_3.9.4      \n[73] xtable_1.8-4       class_7.3-22       glue_1.6.2         janitor_2.2.0     \n[77] tools_4.3.2        shinystan_2.6.0    lme4_1.1-33        colourpicker_1.2.0\n[81] grid_4.3.2         QuickJSR_1.1.3     crosstalk_1.2.0    colorspace_2.1-0  \n[85] nlme_3.1-163       cli_3.6.1          fansi_1.0.6        V8_4.3.0          \n[89] gtable_0.3.4       digest_0.6.33      farver_2.1.1       htmlwidgets_1.6.2 \n[93] htmltools_0.5.6    lifecycle_1.0.4    mime_0.12          shinythemes_1.2.0 \n[97] MASS_7.3-60       \n```\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n\n::::: {.panel-tabset}\n\n\n\n:::::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}