{
  "hash": "157c97e2fc7c24f8c4f90a1527bd567c",
  "result": {
    "markdown": "---\ntitle: \"9: Posterior Inference\"\nauthor: \"Derek Sollberger\"\ndate: \"2024-02-27\"\n# execute:\n#   cache: true\n# format:\n#   revealjs:\n#     scrollable: true\nformat:\n  html:\n    toc: true\n# params:\n#   heavy_chunks: \"true\"\n  # heavy_chunks: \"false\"\n---\n\n\n\\newcommand{\\ds}{\\displaystyle}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"bayesrules\")\nlibrary(\"infer\") #for frequentist approaches\nlibrary(\"patchwork\")\nlibrary(\"tidyverse\")\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n\n# Data\n\n## NEON\n\n\"The National Science Foundation's National Ecological Observatory Network ([NEON](https://www.neonscience.org/about)) is a continental-scale observation facility operated by Battelle and designed to collect long-term **open access ecological data** to better understand how U.S. ecosystems are changing.\"\n\n## NEON Field Sites\n\n\"NEON's aquatic and terrestrial sites are [strategically located](https://www.neonscience.org/field-sites/explore-field-sites) across the U.S. within 20 ecoclimatic Domains that represent regions of distinct landforms, vegetation, climate and ecosystem dynamics.\"\n\n![NEON Field Sites](neon_site_map.png)\n\n## NEON Forecasts Challenge\n\n:::: {.columns}\n\n::: {.column width=\"67%\"}\n\"The National Science Foundation funded Ecological Forecasting Initiative Research Coordination Network (EFI-RCN) is hosting a NEON Ecological Forecast Challenge with the goal to create a community of practice that builds capacity for ecological forecasting by leveraging NEON data products. The Challenge revolves around the five theme areas listed below that span aquatic and terrestrial systems, and population, community, and ecosystem processes across a broad range of ecoregions that uses data collected by NEON.\"\t\n:::\n\n::: {.column width=\"33%\"}\n![NEON Forecasts Themes](neon_forecasts_challenge.png)\n:::\n\n::::\n\n## neon4casts package\n\nThe `neon4cast` [package](https://github.com/eco4cast/neon4cast) \"provides a collection of convenient helper utilities for anyone entering the EFI NEON Forecasting Challenge.\"\n\n* real-world data\n* updated nearly daily\n* very easy API access\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_df <- readr::read_csv(\"https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz\")\n```\n:::\n\n\n## Alternative Data Source: AQICN\n\n* [World Air Quality Index Project](https://aqicn.org/station/@402871/#/z/12)\n* API: [Purple Air](https://community.purpleair.com/t/making-api-calls-with-the-purpleair-api/180)\n\n## Data Product\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(raw_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  datetime   site_id variable observation\n  <date>     <chr>   <chr>          <dbl>\n1 2016-03-05 ARIK    chla              NA\n2 2016-03-05 ARIK    oxygen            NA\n3 2016-03-06 ARIK    chla              NA\n4 2016-03-06 ARIK    oxygen            NA\n5 2016-03-07 ARIK    chla              NA\n6 2016-03-07 ARIK    oxygen            NA\n```\n:::\n:::\n\n\n\n## Data Wrangling\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df <- raw_df %>% \n    pivot_wider(names_from = \"variable\", values_from = \"observation\")\n\nhead(aquatic_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  datetime   site_id  chla oxygen temperature\n  <date>     <chr>   <dbl>  <dbl>       <dbl>\n1 2016-03-05 ARIK       NA     NA          NA\n2 2016-03-06 ARIK       NA     NA          NA\n3 2016-03-07 ARIK       NA     NA          NA\n4 2016-03-08 ARIK       NA     NA          NA\n5 2016-03-09 ARIK       NA     NA          NA\n6 2016-03-10 ARIK       NA     NA          NA\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(aquatic_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"datetime\"    \"site_id\"     \"chla\"        \"oxygen\"      \"temperature\"\n```\n:::\n:::\n\n\n\n# Exploratory Data Analyses\n\n## Variables\n\n:::: {.panel-tabset}\n\n## Timeframe\n\nWe have about 7 years of daily data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |> select(datetime) |> slice(1, n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 1\n  datetime  \n  <date>    \n1 2016-03-05\n2 2024-02-24\n```\n:::\n:::\n\n\n## Field Sites\n\n* [https://www.neonscience.org/field-sites/about-field-sites](https://www.neonscience.org/field-sites/about-field-sites)\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |> select(site_id) |> distinct() |> as.vector()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$site_id\n [1] \"ARIK\" \"BARC\" \"BIGC\" \"BLDE\" \"BLUE\" \"BLWA\" \"CARI\" \"COMO\" \"CRAM\" \"CUPE\"\n[11] \"FLNT\" \"GUIL\" \"HOPB\" \"KING\" \"LECO\" \"LEWI\" \"LIRO\" \"MART\" \"MAYF\" \"MCDI\"\n[21] \"MCRA\" \"OKSR\" \"POSE\" \"PRIN\" \"PRLA\" \"PRPO\" \"REDB\" \"SUGG\" \"SYCA\" \"TECR\"\n[31] \"TOMB\" \"TOOK\" \"WALK\" \"WLOU\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |> group_by(site_id) |> count() |> select(site_id, n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 34 × 2\n# Groups:   site_id [34]\n   site_id     n\n   <chr>   <int>\n 1 ARIK     2912\n 2 BARC     2307\n 3 BIGC     2113\n 4 BLDE     1980\n 5 BLUE     1978\n 6 BLWA     1573\n 7 CARI     1236\n 8 COMO     2463\n 9 CRAM     1150\n10 CUPE     2107\n# ℹ 24 more rows\n```\n:::\n:::\n\n\n## Chlorophyll-a\n\n* non-wadeable river sites (\"lakes\")\n* \"Phytoplankton biomass are the base of the aquatic food-web and an important indicator of water quality for managers.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |>\n  ggplot(aes(x = chla)) +\n  geom_density(color = \"darkgreen\", linewidth = 3) +\n  labs(title = \"Chlorophyll-a Concentration\",\n       subtitle = \"Data Source: NEON Forecasts\",\n       caption = \"SML 320\") +\n  theme_minimal() +\n  xlim(0, 50)\n```\n\n::: {.cell-output-display}\n![](09_posterior_inference_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n## Focus: Lewis Run\n\nThe [Lewis Run NEON station](https://www.neonscience.org/field-sites/lewi) is located 60 miles west of Washingon DC.  It is in the \"Mid-Atlantic\" region of the NEON stations, and it is perhaps the closest in climate to Princeton, New Jersey.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |> filter(site_id == \"LEWI\") |> tail()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  datetime   site_id  chla oxygen temperature\n  <date>     <chr>   <dbl>  <dbl>       <dbl>\n1 2024-02-19 LEWI       NA   6.47        6.80\n2 2024-02-20 LEWI       NA   8.10        6.62\n3 2024-02-21 LEWI       NA   3.31        7.24\n4 2024-02-22 LEWI       NA  NA           7.76\n5 2024-02-23 LEWI       NA  NA           8.59\n6 2024-02-24 LEWI       NA  NA           8.82\n```\n:::\n:::\n\n\n## Oxygen versus Temperature\n\n* dissolved oxygen concentrations less than 2 mg/L are considered **hypoxic**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlewi_df <- aquatic_df |> \n  filter(site_id == \"LEWI\") |>\n  filter(!is.na(oxygen)) |>\n  mutate(hypoxic = oxygen < 2)\n\naquatic_df |>\n  ggplot() +\n  geom_point(aes(x = temperature, y = oxygen),\n             color = \"gray50\") +\n  geom_point(aes(x = temperature, y = oxygen, color = hypoxic),\n             data = lewi_df, size = 3) +\n  labs(title = \"Hypoxia in Lewis Run?\",\n       subtitle = \"Data Source: NEON Forecasts\",\n       caption = \"SML 320\") +\n  scale_color_manual(values = c(\"blue\", \"red\")) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](09_posterior_inference_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n::::\n\n\n# Credible Intervals\n\n## Frequentist Approach: Confidence Interval\n\n:::: {.panel-tabset}\n\n## Definition\n\nA **confidence interval** records percentile endpoints of a sampling distribution that was made by resampling the data *with replacement*.\n\n## Code\n\nUsing code from the `infer` package, as seen in the [ModernDive textbook](https://moderndive.com/)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_distribution <- aquatic_df %>% \n  specify(response = oxygen) %>% \n  generate(reps = 1000) %>% \n  calculate(stat = \"mean\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 19159 rows containing missing values.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nSetting `type = \"bootstrap\"` in `generate()`.\n```\n:::\n\n```{.r .cell-code}\npercentile_ci <- bootstrap_distribution %>% \n  get_confidence_interval(level = 0.95, type = \"percentile\")\n```\n:::\n\n\n## Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize(bootstrap_distribution) + \n  shade_confidence_interval(endpoints = percentile_ci)\n```\n\n::: {.cell-output-display}\n![](09_posterior_inference_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n## Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\npercentile_ci\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1     9.18     9.22\n```\n:::\n:::\n\n\n*We are 95% confident* that the true average concentration level in American bodies of water is between 9.18 and 9.22 mg/L.\n\n::::\n\n## Prior\n\nConsidering the oxygen concentration levels, we will model both the prior and observed data as continuous variables, which lends itself to a *normal-normal conjugate pair*.\n\nFor a rather informative prior (perhaps too restrictive), let us get the oxygen concentrations from the year 2023 data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |>\n  filter(between(datetime,\n                 as_date(\"2023-01-01\"), \n                 as_date(\"2023-12-31\"))) |>\n  summarise(mean = mean(oxygen, na.rm = TRUE),\n            sd = sd(oxygen, na.rm = TRUE),\n            n_prior = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n   mean    sd n_prior\n  <dbl> <dbl>   <int>\n1  9.20  2.16   11155\n```\n:::\n:::\n\n\n## Observed Data\n\nThen, let us focus on the year 2024 data (before today).\n\n\n::: {.cell}\n\n```{.r .cell-code}\naquatic_df |>\n  filter(datetime >as_date(\"2024-01-01\")) |>\n  summarise(y_bar = mean(oxygen, na.rm = TRUE),\n            sigma = sd(oxygen, na.rm = TRUE),\n            n_obs = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 3\n  y_bar sigma n_obs\n  <dbl> <dbl> <int>\n1  10.8  1.77  1462\n```\n:::\n:::\n\n\n## Posterior Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayesrules::summarize_normal_normal(\n  #from prior\n  mean = 9.202716, sd = 2.162342,\n  \n  # from observed data\n  sigma = 1.768468, y_bar = 10.83557, n = 1462\n) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      model    mean    mode    var     sd\n1     prior  9.2027  9.2027 4.6757 2.1623\n2 posterior 10.8348 10.8348 0.0021 0.0462\n```\n:::\n:::\n\n\n## Credible Interval\n\nTo get a 95 percent credible interval, retrieve the locations of the 2.5 and 97.5 percentiles from the posterior distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(c(0.025, 0.975), mean = 10.8348, sd = 0.0462)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10.74425 10.92535\n```\n:::\n:::\n\n\n## Inference and Commentary\n\nThe posterior oxygen concentration levels are between 10.74 and 10.93 mg/L.\n\n* So far, it appears that credible intervals are smaller than confidence intervals (partly because of noting sample sizes)\n* We did not have to aim for 95% credibility\n* We did not have to retrieve the \"middle\" 95%\n* Do we have \"recency bias\"?\n\n\n# NHST: One-Sided\n\n## Frequentist Approach\n\n:::: {.panel-tabset}\n\n## Null Hypothesis\n\nRecall that hypoxia is classified as having dissolved oxygen concentration levels under 2 mg/L.\n\n$$\\text{H}_{o}: \\mu = 2$$\n$$\\text{H}_{a}: \\mu < 2$$\n\n## Definition\n\nIn frequentist null hypothesis significance testing (NHST), the **p-value** is the probability of encountering results that are at least as extreme as the observed results under the assumption that the null hypothesis is true.\n\n* p-value < 0.05: *reject* the null hypothesis\n* p-value >= 0.05: *fail to reject* the null hypothesis\n\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_mean <- aquatic_df |>\n  specify(response = oxygen) |>\n  calculate(stat = \"mean\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 19159 rows containing missing values.\n```\n:::\n\n```{.r .cell-code}\nnull_distribution <- aquatic_df |>\n  specify(response = oxygen) |>\n  hypothesize(null = \"point\", mu = 2) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"mean\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 19159 rows containing missing values.\n```\n:::\n:::\n\n\n## Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_distribution |>\n  visualise() +\n  shade_p_value(obs_stat = obs_mean, direction = \"less\")\n```\n\n::: {.cell-output-display}\n![](09_posterior_inference_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n## Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_distribution |>\n  get_p_value(obs_stat = obs_mean, direction = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       1\n```\n:::\n:::\n\n\nSince the p-value > 0.05, we *fail to reject* the claim that the dissolved oxygen concentration level in American bodies of water is 2 mg/L.\n\n::::\n\n## Prior and Posterior Probabilities\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n      model    mean    mode    var     sd\n1     prior  9.2027  9.2027 4.6757 2.1623\n2 posterior 10.8348 10.8348 0.0021 0.0462\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_prob <- pnorm(2, mean = 9.2027, sd = 2.1623)\n\nposterior_prob <- pnorm(2, mean = 10.8348, sd = 0.0462)\n```\n:::\n\n\n## Prior and Posterior Odds\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_odds <- prior_prob / (1 - prior_prob)\n\nposterior_odds <- posterior_prob / (1 - posterior_prob)\n```\n:::\n\n\n\n\n## Bayes Factor\n\n$$\\text{Bayes Factor} = \\ds\\frac{\\text{posterior odds}}{\\text{prior odds}}$$\n\n* $BF = 1$: the **plausibility** of $H_{a}$ *did not change* with the observed data\n* $BF > 1$: the **plausibility** of $H_{a}$ *increased* with the observed data\n* $BF < 1$: the **plausibility** of $H_{a}$ *decreased* with the observed data\n\n## Inference\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bayes factor\nBF <- posterior_odds / prior_odds\nBF\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n\nThe plausibility of observing hypoxic conditions *decreased* with the inclusion of the year 2024 data.\n\n\n# NHST: Two-Sided\n\n## Null Hypothesis\n\nFor this example, let us claim that the dissolved oxygen concentration level is \"close\" to 10.7 mg/L\n\n$$\\text{H}_{o}: \\mu \\in (10.6, 10.8)$$\n$$\\text{H}_{a}: \\mu \\notin (10.6, 10.8)$$\n\n## Prior and Posterior Probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_prob <- diff(pnorm(c(10.6, 10.8),\n                         mean = 9.2027, sd = 2.1623))\n\nposterior_prob <- diff(pnorm(c(10.6, 10.8),\n                             mean = 10.8348, sd = 0.0462))\n```\n:::\n\n\n## Bayes Factor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_odds <- prior_prob / (1 - prior_prob)\nposterior_odds <- posterior_prob / (1 - posterior_prob)\nBF <- posterior_odds / prior_odds\nBF\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.747294\n```\n:::\n:::\n\n\nThe plausibility of observing dissolved oxygen concentration level \"near\" 10.7 mg/L *increased* with the inclusion of the year 2024 data.\n\n\n# Footnotes\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.3.2 (2023-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] lubridate_1.9.3  forcats_1.0.0    stringr_1.5.1    dplyr_1.1.4     \n [5] purrr_1.0.2      readr_2.1.5      tidyr_1.3.1      tibble_3.2.1    \n [9] ggplot2_3.4.3    tidyverse_2.0.0  patchwork_1.1.2  infer_1.0.4     \n[13] bayesrules_0.0.2\n\nloaded via a namespace (and not attached):\n  [1] gridExtra_2.3      inline_0.3.19      rlang_1.1.1       \n  [4] magrittr_2.0.3     snakecase_0.11.0   matrixStats_1.0.0 \n  [7] e1071_1.7-13       compiler_4.3.2     loo_2.6.0         \n [10] callr_3.7.3        vctrs_0.6.5        reshape2_1.4.4    \n [13] pkgconfig_2.0.3    crayon_1.5.2       fastmap_1.1.1     \n [16] ellipsis_0.3.2     labeling_0.4.3     utf8_1.2.4        \n [19] threejs_0.3.3      promises_1.2.1     rmarkdown_2.24    \n [22] tzdb_0.4.0         markdown_1.8       ps_1.7.5          \n [25] nloptr_2.0.3       bit_4.0.5          xfun_0.40         \n [28] jsonlite_1.8.7     later_1.3.1        parallel_4.3.2    \n [31] prettyunits_1.2.0  R6_2.5.1           dygraphs_1.1.1.6  \n [34] stringi_1.8.3      StanHeaders_2.32.5 boot_1.3-28.1     \n [37] Rcpp_1.0.11        rstan_2.32.5       knitr_1.43        \n [40] zoo_1.8-12         base64enc_0.1-3    bayesplot_1.10.0  \n [43] httpuv_1.6.11      Matrix_1.6-1.1     splines_4.3.2     \n [46] igraph_1.4.3       timechange_0.3.0   tidyselect_1.2.0  \n [49] rstudioapi_0.15.0  yaml_2.3.8         codetools_0.2-19  \n [52] miniUI_0.1.1.1     curl_5.0.2         processx_3.8.1    \n [55] pkgbuild_1.4.0     lattice_0.21-9     plyr_1.8.8        \n [58] withr_3.0.0        shiny_1.7.5        groupdata2_2.0.2  \n [61] evaluate_0.21      survival_3.5-7     proxy_0.4-27      \n [64] RcppParallel_5.1.7 xts_0.13.1         pillar_1.9.0      \n [67] DT_0.28            stats4_4.3.2       shinyjs_2.1.0     \n [70] generics_0.1.3     vroom_1.6.5        hms_1.1.3         \n [73] rstantools_2.3.1   munsell_0.5.0      scales_1.2.1      \n [76] minqa_1.2.5        gtools_3.9.4       xtable_1.8-4      \n [79] class_7.3-22       glue_1.6.2         janitor_2.2.0     \n [82] tools_4.3.2        shinystan_2.6.0    lme4_1.1-33       \n [85] colourpicker_1.2.0 grid_4.3.2         QuickJSR_1.1.3    \n [88] crosstalk_1.2.0    colorspace_2.1-0   nlme_3.1-163      \n [91] cli_3.6.1          fansi_1.0.6        V8_4.3.0          \n [94] gtable_0.3.4       digest_0.6.33      farver_2.1.1      \n [97] htmlwidgets_1.6.2  htmltools_0.5.6    lifecycle_1.0.4   \n[100] mime_0.12          rstanarm_2.21.4    bit64_4.0.5       \n[103] shinythemes_1.2.0  MASS_7.3-60       \n```\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\t\n:::\n\n::: {.column width=\"50%\"}\n\n:::\n\n::::\n\n:::: {.panel-tabset}\n\n\n\n::::",
    "supporting": [
      "09_posterior_inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}