{
  "hash": "4da3f741efdf2a349ccc8968fdaa37e4",
  "result": {
    "markdown": "---\ntitle: \"15: Logistic Regression\"\nauthor: \"Derek Sollberger\"\ndate: \"2024-04-02\"\nexecute:\n  cache: true\n# format:\n#   revealjs:\n#     scrollable: true\nformat:\n  html:\n    toc: true\n---\n\n\n\\newcommand{\\ds}{\\displaystyle}\n\n# Logistic Regression\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n**Goal:** Use Bayesian approaches to classification tasks\n\n*Bayes Rules!* Exercise 13.14\n\n![Another Ghostbusters movie came out in 2024](ghostbusters_frozen_empire.png)\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-1_cb67fb70d9052f94c80f7afe0a97f616'}\n\n```{.r .cell-code}\nlibrary(\"bayesrules\")\nlibrary(\"bayesplot\")\nlibrary(\"ggtext\")\nlibrary(\"gt\")\nlibrary(\"janitor\")\nlibrary(\"rstan\")\nlibrary(\"rstanarm\")\nlibrary(\"tidyverse\")\n\nknitr::opts_chunk$set(echo = TRUE)\n\ndata(pulse_of_the_nation)\npulse_df <- pulse_of_the_nation\n\npulse_df$education <- factor(pulse_df$education,\n                             levels = c(\"Graduate degree\",\n                                        \"College degree\",\n                                        \"Some college\",\n                                        \"High school\",\n                                        \"Other\"))\npulse_df$robots <- factor(pulse_df$robots,\n                          levels = c(\"Likely\", \"Unlikely\"))\npulse_df$ghosts <- factor(pulse_df$ghosts,\n                          levels = c(\"Yes\", \"No\"))\n```\n:::\n\n:::\n\n::::\n\n# Data\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n* source: [Pulse of the Nation](https://thepulseofthenation.com/#intro) survey by Cards Against Humanity\n* Poll 1: September 2017\n\n* 1000 observations\n* 15 variables\n\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n![Pulse of the Nation](prulse_of_the_nation.png)\n:::\n\n::::\n\n## Exploratory Data Analyses\n\n::::: {.panel-tabset}\n\n## Income\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-2_e06d23b1f310e882d67ef61889ec51f3'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-3_b0ef2d88761912a4f094a25fdc23a644'}\n\n```{.r .cell-code}\npulse_df |>\n  ggplot(aes(x = income)) +\n  geom_density(fill = \"green\") +\n  labs(title = \"Pulse of the Nation\",\n       subtitle = \"Income of participants\",\n       caption = \"SML 320\",\n       x = \"income (thousands of dollars)\",\n       y = \"\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank())\n```\n:::\n\n\n## Age\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-4_2fceb697d2bcb57cc948a950787f0eca'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-5_de940988a2e5a01f92b6539a0230881d'}\n\n```{.r .cell-code}\npulse_df |>\n  ggplot(aes(x = age)) +\n  geom_density(fill = \"purple\") +\n  labs(title = \"Pulse of the Nation\",\n       subtitle = \"Age of participants\",\n       caption = \"SML 320\",\n       x = \"age\",\n       y = \"\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank())\n```\n:::\n\n\n## Education\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-6_5398d2bb85693228dcdd4640fee5df6a'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-7_69b6423b5a3918662b9be28f8873e864'}\n\n```{.r .cell-code}\npulse_df |>\n  ggplot(aes(x = education, fill = education)) +\n  geom_bar(stat = \"count\") +\n  labs(title = \"Pulse of the Nation\",\n       subtitle = \"Education attainment of participants\",\n       caption = \"SML 320\",\n       x = \"education\",\n       y = \"count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n:::\n\n\n## Robots\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-8_3b307e0a8c978d8dc6efe4387ef24f89'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-9_c66106e2c7ebda666b8c274e714f3025'}\n\n```{.r .cell-code}\npulse_df |>\n  ggplot(aes(x = robots, fill = robots)) +\n  geom_bar(stat = \"count\") +\n  labs(title = \"Pulse of the Nation\",\n       subtitle = \"Is it likely that robots would take your jobs within the next decade\",\n       caption = \"September 2017\",\n       x = \"\",\n       y = \"count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n:::\n\n\n## Ghosts\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-10_aaf4fb46d465a24f614547593705bfdc'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-11_7f84d1fb0cd574accc86bd449af67a5f'}\n\n```{.r .cell-code}\npulse_df |>\n  ggplot(aes(x = ghosts, fill = ghosts)) +\n  geom_bar(stat = \"count\") +\n  labs(title = \"Pulse of the Nation\",\n       subtitle = \"Do you believe in ghosts?\",\n       caption = \"September 2017\",\n       x = \"\",\n       y = \"count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n:::\n\n\n\n:::::\n\n## Variables\n\n:::: {.columns}\n\n::: {.column width=\"40%\"}\n### Response Variable\n\n$Y$: `ghosts`\n\n* *binary variable*: did the survey participant believe in ghosts?\n\n### Prediction\n\nWhat percentage of 21-year-olds who make $75,000 believe in ghosts?\n\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"50%\"}\n### Predictor Variables\n\n* $X_{1}$: `income`\n* $X_{2}$: `age`\n* $X_{3}$: `education`\n* $X_{4}$: `robots`\n:::\n\n::::\n\n# Odds\n\n::::: {.panel-tabset}\n\n## Definition\n\nThe notion of **odds** is related to probability.  If we have a probability computed with a value of $\\pi$, then the odds are\n\n$$\\text{odds} = \\frac{\\pi}{1 - \\pi}$$\n\n* $\\pi \\in [0,1]$\n* odds $\\in [0 \\infty)$\n\n## Example\n\nThe observed probability (scaled frequency) of believing in ghosts is 37.9 percent.\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-12_6f1f5983369a4651d57ad3d0a79403c1'}\n\n```{.r .cell-code}\npulse_df |> \n  janitor::tabyl(ghosts) |> \n  janitor::adorn_totals()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n ghosts    n percent\n    Yes  379   0.379\n     No  621   0.621\n  Total 1000   1.000\n```\n:::\n:::\n\n\nCompute the odds of believing in ghosts.\n\n$$\\text{odds} = \\frac{\\pi}{1 - \\pi} = \\frac{0.379}{1 - 0.379} = 0.610$$\nThe odds of believing in ghosts are 379 to 621.\n\n## Inverse\n\nIf we know the odds of an event, the associated probability is\n\n$$\\pi = \\frac{\\text{odds}}{1 + \\text{odds}}$$\n\n## Example\n\nAmong the participants with a college degree, the odds of believing in ghosts was 45 to 268.  What was the probability of randomly selecting a person in that set that believed in ghosts?\n\n$$\\pi = \\frac{\\text{odds}}{1 + \\text{odds}} = \\frac{\\frac{45}{268}}{1 + \\frac{45}{268}} \\approx 0.1438$$\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-13_ab314ca1aa7f9583d2b7cae2166406b0'}\n\n```{.r .cell-code}\npulse_df |>\n  filter(education == \"College degree\") |>\n  janitor::tabyl(robots) |> \n  janitor::adorn_totals()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   robots   n percent\n   Likely  45 0.14377\n Unlikely 268 0.85623\n    Total 313 1.00000\n```\n:::\n:::\n\n\n:::::\n\n\n# Logistic Model\n\n::::: {.panel-tabset}\n\n## Definition\n\n$$Y_{i} | \\beta_{0}, \\beta_{1} \\sim \\text{Bern}(\\pi_{i}) \\quad\\text{with}\\quad \\ln\\left(\\frac{\\pi_{i}}{1 - \\pi_{i}}\\right) = \\beta_{0} + \\beta_{1}X_{i1} ...$$\n\n$$\\frac{\\pi_{i}}{1 - \\pi_{i}} = e^{\\beta_{0} + \\beta_{1}X_{i1}} \\quad\\text{and}\\quad \\pi_{i} = \\frac{e^{\\beta_{0} + \\beta_{1}X_{i1}}}{1 + e^{\\beta_{0} + \\beta_{1}X_{i1}}}$$\n\n## Viz\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-14_27c1d9d5e4e0e29f5f52206cee44f41c'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-15_6a091ef5b60d147a86558d24b5367381'}\n\n```{.r .cell-code}\npulse_df |>\n  ggplot(aes(x = age, y = income, color = ghosts)) +\n  geom_point() +\n  labs(title = \"Pulse of the Nation\",\n       subtitle = \"Do you believe in ghosts?\",\n       caption = \"September 2017\",\n       x = \"age\",\n       y = \"income\") +\n  theme_minimal()\n```\n:::\n\n\n## Stan\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-16_7da1d5532c6bbda9e8cc86e398abd7f9'}\n\n```{.r .cell-code}\nlog_reg_mod_1 <- rstanarm::stan_glm(\n  formula = ghosts ~ income + age,\n  data = pulse_df,\n  family = binomial, #changed here\n  chains = 4, iter = 5000*2, refresh = 0, seed = 320)\n```\n:::\n\n\n## Diagnostics\n\n::: {.callout-note collapse=\"true\"}\n## Function\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-17_4679edff740b62d16fe3b5ca16b42840'}\n\n```{.r .cell-code}\nmodel_diagnostics <- function(the_stan_model){\n  p1 <- bayesplot::mcmc_trace(the_stan_model, size = 0.1) +\n  labs(title = \"MCMC Traces\")\n  print(p1)\n  \n  p2 <- bayesplot::mcmc_dens_overlay(the_stan_model) +\n  labs(title = \"Density Plots\")\n  print(p2)\n  \n  p3 <- bayesplot::mcmc_acf(the_stan_model) +\n  labs(title = \"Autocorrelations\")\n  print(p3)\n  \n  # effective sample size\n  print(\"Effective Sample Size:\")\n  print(bayesplot::neff_ratio(the_stan_model))\n  \n  # split-R metric\n  print(\"R-Hat\")\n  print(bayesplot::rhat(the_stan_model))\n}\n```\n:::\n\n\n:::\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-18_81a763fd3122386b344cd5f1004cfb9c'}\n\n```{.r .cell-code}\nmodel_diagnostics(log_reg_mod_1)\n```\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-18-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Effective Sample Size:\"\n(Intercept)      income         age \n    0.94680     0.99060     0.94225 \n[1] \"R-Hat\"\n(Intercept)      income         age \n  0.9998781   0.9998473   0.9999707 \n```\n:::\n:::\n\n\n## Model Stats\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-19_c05fe6fecdb1dad5bc701a7b84e767ea'}\n\n```{.r .cell-code}\nbroom.mixed::tidy(log_reg_mod_1,\n                  conf.int = TRUE, conf.level = 0.90) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term        estimate std.error conf.low conf.high\n  <chr>          <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)  -0.142     0.240   -0.536     0.26  \n2 income        0.0021    0.0012   0.0001    0.0041\n3 age           0.0091    0.004    0.0026    0.0157\n```\n:::\n:::\n\n\n:::::\n\n\n# Interpretation\n\n::::: {.panel-tabset}\n\n## Ideas\n\n$$\\ln(\\text{odds})=\\ln\\left(\\frac{\\pi}{1 - \\pi}\\right)=\\beta_{0}+\\beta_{1}X_{1}+\\cdots+\\beta_{p}X_{p}$$\n\n* intercept: $\\beta_{0}$ is the *log odds*, $e^{\\beta_{0}}$ is the odds\n\n$$\\beta_{i} = \\ln(\\text{odds}_{x+1}) - \\ln(\\text{odds}_{x}) \\quad\\text{and}\\quad e^{\\beta_{i}} = \\frac{\\text{odds}_{x+1}}{\\text{odds}_{x}}$$\n\n* $\\beta_{i}$: change in log odds\n* $e^{\\beta_{i}}$: *multiplicative* change in odds\n\n## Intercept\n\nWhen $X_{1} = 0$ and $X_{2} = 0$,\n\n$$\\begin{array}{rrrr}\n\\text{log odds: } & \\beta_{0} & \\approx & -0.1422 \\\\\n\\text{odds: } & e^{\\beta_{0}} & \\approx & 0.8674\n\\end{array}$$\n\nOverall, since the odds are less than one, it is less likely to encounter a person who believes in ghosts than a person who doesn't believe in ghosts.\n\n## Coefficients\n\n$$\\beta_{1} \\approx 0.0021 \\quad\\rightarrow\\quad e^{\\beta_{1}} \\approx 1.0021$$\n\nFor each $1000 increase in annual income, the odds of believing in ghosts increases by about 0.21 percent.\n\n$$\\beta_{2} \\approx 0.0091\t \\quad\\rightarrow\\quad e^{\\beta_{2}} \\approx 1.0091$$\n\nFor each unit increase in age, the odds of believing in ghosts increases by about 0.91 percent.\n\n## Autoscale\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-20_a48cff3778f271c9a7bb11b6b54f72e4'}\n\n```{.r .cell-code}\nprior_summary(log_reg_mod_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPriors for model 'log_reg_mod_1' \n------\nIntercept (after predictors centered)\n ~ normal(location = 0, scale = 2.5)\n\nCoefficients\n  Specified prior:\n    ~ normal(location = [0,0], scale = [2.5,2.5])\n  Adjusted prior:\n    ~ normal(location = [0,0], scale = [0.044,0.150])\n------\nSee help('prior_summary.stanreg') for more details\n```\n:::\n:::\n\n\n$$Y_{i} | \\beta_{0}, \\beta_{1} \\sim \\text{Bern}(\\pi_{i}) \\quad\\text{with}\\quad \\ln\\left(\\frac{\\pi_{i}}{1 - \\pi_{i}}\\right) = \\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2}$$\n$$\\begin{array}{rcl}\n  \\beta_{0c} & \\sim & \\text{N}(0, 2.5^2) \\\\\n  \\beta_{1} & \\sim & \\text{N}(0, 0.044^2) \\\\\n  \\beta_{2} & \\sim & \\text{N}(0, 0.150^2) \\\\\n\\end{array}$$\n\n## Priors\n\n$$\\beta_{0c}: \\quad \\left( e^{-5}, e^{5} \\right)$$\n\nThe prior odds for believing in ghosts varied largely.\n\n$$\\beta_{1}: \\quad \\left( e^{-0.088}, e^{0.088} \\right)$$\nThe prior odds change for income was between decreasing by 8.6 percent and increasing by 9.1 percent.\n\n$$\\beta_{2}: \\quad \\left( e^{-0.3}, e^{0.3} \\right)$$\nThe prior odds change for income was between decreasing by 26 percent and increasing by 35 percent.\n\n## Posterior\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-21_9440a2e76998bc88b052de014095a7e0'}\n\n```{.r .cell-code}\n# change in log odds\nrstanarm::posterior_interval(log_reg_mod_1, prob = 0.90) |>\n  round(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 5%    95%\n(Intercept) -0.5364 0.2600\nincome       0.0001 0.0041\nage          0.0026 0.0157\n```\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-22_8226738aeedcc30aeafe0cd3b4405f88'}\n\n```{.r .cell-code}\n# multiplicative change in odds\nexp(rstanarm::posterior_interval(log_reg_mod_1, prob = 0.90)) |>\n  round(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                5%    95%\n(Intercept) 0.5848 1.2970\nincome      1.0001 1.0042\nage         1.0026 1.0158\n```\n:::\n:::\n\n\n:::::\n\n\n# Prediction\n\n## Simulation\n\nWhat percentage of 21-year-olds who make $75,000 believe in ghosts?\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-23_0bdcb87d72c048afb2e1d4e1f12af3bd'}\n\n```{.r .cell-code}\nset.seed(320)\nlog_reg_mod_1_df <- as.data.frame(log_reg_mod_1) |>\n  mutate(log_odds = `(Intercept)` + income*75 + age*21,\n         odds = exp(log_odds),\n         prob = odds / (1 + odds),\n         Y = rbinom(20000, size = 1, prob = prob))\n```\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-24_51c9e52d9b04e68b9938a0b086efe9ce'}\n\n```{.r .cell-code}\nlog_reg_mod_1_df |>\n  mutate_if(is.numeric, round, digits = 4) |>\n  slice_sample(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   (Intercept) income     age log_odds   odds   prob Y\n1      -0.0165 0.0011  0.0081   0.2364 1.2667 0.5588 1\n2       0.2884 0.0028 -0.0008   0.4830 1.6209 0.6184 1\n3      -0.2852 0.0034  0.0128   0.2402 1.2715 0.5598 1\n4      -0.2206 0.0018  0.0109   0.1463 1.1576 0.5365 1\n5      -0.3701 0.0024  0.0115   0.0559 1.0575 0.5140 0\n6      -0.1566 0.0024  0.0074   0.1799 1.1971 0.5448 0\n7      -0.1805 0.0029  0.0066   0.1775 1.1942 0.5443 0\n8      -0.1173 0.0003  0.0129   0.1723 1.1880 0.5430 1\n9      -0.4068 0.0028  0.0116   0.0493 1.0505 0.5123 0\n10      0.1703 0.0025  0.0029   0.4165 1.5166 0.6026 1\n```\n:::\n:::\n\nWhat percentage of 21-year-olds who make $75,000 believe in ghosts?\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-25_9f83e9da93599fc8bee1936b061e0f7e'}\n\n```{.r .cell-code}\nmean(log_reg_mod_1_df$Y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.54835\n```\n:::\n:::\n\n\n## Cutoff\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-26_8cd20a3e6934308f7ed6d3e28a6287ab'}\n\n```{.r .cell-code}\nset.seed(320)\n\n# make 20000 predictions\nghost_preds <- rstanarm::posterior_predict(\n  log_reg_mod_1, newdata = pulse_df)\n\nghost_classifications <- pulse_df |>\n  mutate(ghost_prob = colMeans(ghost_preds),\n         ghost_class = ifelse(ghost_prob >= 0.60, 1, 0)) |>\n  select(income, age, ghost_prob, ghost_class, ghosts)\n\nhead(ghost_classifications, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 5\n   income   age ghost_prob ghost_class ghosts\n    <dbl> <dbl>      <dbl>       <dbl> <fct> \n 1      8    64      0.608           1 Yes   \n 2     68    56      0.625           1 No    \n 3     46    63      0.629           1 No    \n 4     51    48      0.601           1 No    \n 5    100    32      0.590           0 Yes   \n 6     54    64      0.634           1 No    \n 7     83    61      0.641           1 Yes   \n 8    114    64      0.666           1 No    \n 9     90    64      0.660           1 No    \n10      5    68      0.621           1 No    \n```\n:::\n:::\n\n\n## Confusion Matrix\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-27_dfa585b44d08c759136b102b371d4f02'}\n\n```{.r .cell-code}\nghost_classifications |>\n  janitor::tabyl(ghosts, ghost_class) |>\n  adorn_totals(c(\"row\", \"col\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n ghosts   0   1 Total\n    Yes 135 244   379\n     No 172 449   621\n  Total 307 693  1000\n```\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Formulas\n\n$$\\text{accuracy } = \\frac{TP + TN}{TP + FN + FP + TN}$$\n$$\\text{sensitivity } = \\frac{TP}{TP + FN}$$\n$$\\text{specificity } = \\frac{TN}{FP + TN}$$\n$$\\text{F-score } = \\frac{2*TP}{2*TP + FN + FP}$$\n\nSource: [Wikipedia page on sensitivity and specificity](https://en.wikipedia.org/wiki/Sensitivity_and_specificity)\n\n:::\n\n\n# Confusion\n\n## Classification\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-28_623fd671dca38994c47ffd8467917cbc'}\n\n```{.r .cell-code}\nset.seed(320)\nclass_results <- bayesrules::classification_summary(\n  model = log_reg_mod_1,\n  data = pulse_df,\n  cutoff = 0.6\n)\n```\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-29_8c1bf761dcf3248af8bb288db6b32de7'}\n\n```{.r .cell-code}\nclass_results$confusion_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   y   0   1\n Yes 135 244\n  No 172 449\n```\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-30_0a23bccb0c5fafd99d47c8b01dbd80f3'}\n\n```{.r .cell-code}\nclass_results$accuracy_rates |> round(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                       \nsensitivity      0.7230\nspecificity      0.3562\noverall_accuracy 0.5840\n```\n:::\n:::\n\n\n## Cutoff\n\nHow do we choose a cutoff value?\n\n::::: {.panel-tabset}\n\n## Loop\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-31_4ac4a4fe61eb61bdfc2fa20849c17859'}\n\n```{.r .cell-code}\nN <- 11 #resolution\ncutoff_vals <- seq(0.5, 1.0, length.out = N)\n\naccuracies <-    rep(NA, N)\nsensitivities <- rep(NA, N)\nspecificities <- rep(NA, N)\n\nfor(i in 1:length(cutoff_vals)){\n  this_class_result <- bayesrules::classification_summary(\n    model = log_reg_mod_1,\n    data = pulse_df,\n    cutoff = cutoff_vals[i]\n  )\n  \n  these_metrics <- unlist(this_class_result$accuracy_rates)\n  \n  accuracies[i]    <- these_metrics[3]\n  sensitivities[i] <- these_metrics[1]\n  specificities[i] <- these_metrics[2]\n}\n\ncutoff_df <- data.frame(cutoff_vals, accuracies, sensitivities, specificities)\n```\n:::\n\n\n## Viz\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-32_51a8937d9d3068ae4deaea5063f14818'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n* As we lower $c$, sensitivity increases, but specificity decreases.\n* As we increase $c$, specificity increases, but sensitivity decreases.\n* Perhaps a cutoff value around 0.62 would be good here.\n\n## Code\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-33_2dcd5e954612fbd33cc1d8b10a08f6a8'}\n\n```{.r .cell-code}\nsubtitle_string <- \"<span style='color:#ff00ff'>Accuracy</span>,<span style='color:#0000ff'>Sensitivity</span>, and <span style='color:#ff0000'>Specificity</span>\"\n\ncutoff_df |>\n  ggplot() +\n  geom_point(aes(x = cutoff_vals, y = specificities),\n             color = \"#ff0000\", size = 5) +\n  geom_line(aes(x = cutoff_vals, y = specificities),\n             color = \"#ff0000\", linewidth = 1) +\n  geom_point(aes(x = cutoff_vals, y = sensitivities),\n             color = \"#0000ff\", size = 5) +\n  geom_line(aes(x = cutoff_vals, y = sensitivities),\n             color = \"#0000ff\", linewidth = 1) +\n  geom_point(aes(x = cutoff_vals, y = accuracies),\n             color = \"#ff00ff\", size = 5) +\n  geom_line(aes(x = cutoff_vals, y = accuracies),\n             color = \"#ff00ff\", linewidth = 1) +\n  labs(title = \"Confusion Matrix Metrics\",\n       subtitle = subtitle_string,\n       caption = \"SML 320\",\n       x = \"cutoff value\",\n       y = \"metric value\") +\n  theme_minimal() +\n  theme(plot.subtitle = element_markdown()) #use ggtext package\n```\n:::\n\n\n:::::\n\n## Cross Validation\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-34_5f7fb3b3d584c9d16a8756aa58f64802'}\n\n```{.r .cell-code}\nset.seed(320)\nlog_reg_mod_1_cv <- bayesrules::classification_summary_cv(\n  model = log_reg_mod_1, data = pulse_df,\n  cutoff = 0.62, k = 10)\n\nlog_reg_mod_1_cv$cv\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sensitivity specificity overall_accuracy\n1    0.553233   0.5416136            0.547\n```\n:::\n:::\n\n\n\n# Extended Model\n\n::::: {.panel-tabset}\n\n## Stan\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-35_60f97f7111d2f51eebe33c82be412f07'}\n\n```{.r .cell-code}\nlog_reg_mod_2 <- rstanarm::stan_glm(\n  formula = ghosts ~ income + age + education + robots,\n  data = pulse_df,\n  family = binomial, #changed here\n  chains = 4, iter = 5000*2, refresh = 0, seed = 320)\n```\n:::\n\n\n## Diagnostics\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-36_79b4ec33f2ac1d91cd429568c9758a00'}\n\n```{.r .cell-code}\nmodel_diagnostics(log_reg_mod_2)\n```\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-36-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-36-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Effective Sample Size:\"\n            (Intercept)                  income                     age \n                0.57475                 0.82640                 1.03945 \neducationCollege degree   educationSome college    educationHigh school \n                0.51180                 0.48165                 0.48780 \n         educationOther          robotsUnlikely \n                0.76020                 0.95700 \n[1] \"R-Hat\"\n            (Intercept)                  income                     age \n              1.0001413               0.9999428               0.9999225 \neducationCollege degree   educationSome college    educationHigh school \n              1.0004564               1.0002608               1.0003218 \n         educationOther          robotsUnlikely \n              0.9999068               0.9999724 \n```\n:::\n:::\n\n\n## Model Stats\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-37_a5136cf543c652e11430c7eb794fc073'}\n\n```{.r .cell-code}\nbroom.mixed::tidy(log_reg_mod_2,\n                  conf.int = TRUE, conf.level = 0.90) |>\n  mutate_if(is.numeric, round, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 5\n  term                    estimate std.error conf.low conf.high\n  <chr>                      <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)               0.462     0.331   -0.0856    1.01  \n2 income                    0.0008    0.0013  -0.0013    0.003 \n3 age                       0.0083    0.004    0.0018    0.0148\n4 educationCollege degree  -0.307     0.195   -0.636     0.012 \n5 educationSome college    -0.555     0.204   -0.892    -0.224 \n6 educationHigh school     -0.647     0.223   -1.02     -0.278 \n7 educationOther           -0.909     0.521   -1.76     -0.0454\n8 robotsUnlikely           -0.0601    0.171   -0.344     0.214 \n```\n:::\n:::\n\n\n## Cross Validation\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-38_638a6aa41b6cb047dc41061ebc9ee301'}\n\n```{.r .cell-code}\nset.seed(320)\nlog_reg_mod_2_cv <- bayesrules::classification_summary_cv(\n  model = log_reg_mod_2, data = pulse_df,\n  cutoff = 0.62, k = 10)\n```\n:::\n\n\n:::::\n\n# Model Selection\n\n$$\\ln\\left(\\frac{\\pi_{i}}{1 - \\pi_{i}}\\right) = \\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2}$$\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-39_fb83a719f7987cd7abb11784215c43c8'}\n\n```{.r .cell-code}\nlog_reg_mod_1_cv$cv |> round(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sensitivity specificity overall_accuracy\n1      0.5532      0.5416            0.547\n```\n:::\n:::\n\n\n$$\\ln\\left(\\frac{\\pi_{i}}{1 - \\pi_{i}}\\right) = \\beta_{0} + \\beta_{1}X_{i1} + \\beta_{2}X_{i2} + \\beta_{3}X_{i3} + \\beta_{4}X_{i4}$$\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-40_3b0d44280f47332a08eb9bd949ee37c6'}\n\n```{.r .cell-code}\nlog_reg_mod_2_cv$cv |> round(digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sensitivity specificity overall_accuracy\n1      0.5136      0.5847            0.539\n```\n:::\n:::\n\n\n\n# Posterior Interval\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-41_4253daf0befc36ccd8517e8c2ba4c304'}\n\n```{.r .cell-code}\nproportion_calc <- function(x){ mean(x == 1) }\nrstanarm::pp_check(log_reg_mod_1, binwidth = 0.01,\n                   plotfun = \"stat\", stat = \"proportion_calc\") +\n  xlab(\"proportion believes in ghosts\")\n```\n\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-42_223a2ad17cc61163550c86e37ed201d0'}\n::: {.cell-output-display}\n![](15_logistic_regression_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-43_898c5c1d0da684b5372e9a8a9fbda486'}\n\n```{.r .cell-code}\nCI_left <- quantile(log_reg_mod_1_df$prob, 0.05)\nCI_right <- quantile(log_reg_mod_1_df$prob, 0.95)\n\nlog_reg_mod_1_df |>\n  ggplot(aes(x = prob)) +\n  geom_density(color = \"#121212\", fill = \"#E77500\") +\n  geom_vline(xintercept = CI_left, color = \"#121212\", \n             linetype = 2, linewidth = 3) +\n  geom_vline(xintercept = CI_right, color = \"#121212\", \n             linetype = 2, linewidth = 3) +\n  labs(title = \"For a 21-year-old making $75k/year, belief in ghosts\",\n       subtitle = paste0(\"Has a 90-percent credible interval of (\", round(CI_left,2),\n                         \", \", round(CI_right,2), \")\"),\n       caption = \"SML 320\",\n       x = \"proportion\",\n       y = \"\") +\n  theme_minimal() +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank())\n```\n:::\n\n\n\n# Footnotes\n\n* [Bayesian Logistic Regression Models](https://people.stat.sc.edu/hitchcock/stat535slides13BRBhandout.pdf) by Dr David B Hitchcock at the University of South Carolina\n\n::: {.callout-note collapse=\"true\"}\n## Session Info\n\n\n::: {.cell hash='15_logistic_regression_cache/html/unnamed-chunk-44_a7f054a0acbd356e255a8edb16ff2574'}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.3.2 (2023-10-31 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 10 x64 (build 19045)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] ggtext_0.1.2       janitor_2.2.0      lubridate_1.9.3    forcats_1.0.0     \n [5] stringr_1.5.1      dplyr_1.1.4        purrr_1.0.2        readr_2.1.5       \n [9] tidyr_1.3.1        tibble_3.2.1       ggplot2_3.4.3      tidyverse_2.0.0   \n[13] rstanarm_2.21.4    Rcpp_1.0.11        rstan_2.32.5       StanHeaders_2.32.5\n[17] patchwork_1.1.2    gt_0.9.0           bayesplot_1.10.0   bayesrules_0.0.2  \n\nloaded via a namespace (and not attached):\n [1] gridExtra_2.3      inline_0.3.19      rlang_1.1.1        magrittr_2.0.3    \n [5] snakecase_0.11.0   matrixStats_1.0.0  e1071_1.7-13       compiler_4.3.2    \n [9] loo_2.6.0          callr_3.7.3        vctrs_0.6.5        reshape2_1.4.4    \n[13] pkgconfig_2.0.3    crayon_1.5.2       fastmap_1.1.1      ellipsis_0.3.2    \n[17] labeling_0.4.3     utf8_1.2.4         threejs_0.3.3      promises_1.2.1    \n[21] rmarkdown_2.24     tzdb_0.4.0         markdown_1.8       ps_1.7.5          \n[25] nloptr_2.0.3       xfun_0.40          jsonlite_1.8.7     later_1.3.1       \n[29] parallel_4.3.2     prettyunits_1.2.0  R6_2.5.1           dygraphs_1.1.1.6  \n[33] stringi_1.8.3      boot_1.3-28.1      knitr_1.43         zoo_1.8-12        \n[37] base64enc_0.1-3    httpuv_1.6.11      Matrix_1.6-1.1     splines_4.3.2     \n[41] igraph_1.4.3       timechange_0.3.0   tidyselect_1.2.0   rstudioapi_0.15.0 \n[45] yaml_2.3.8         codetools_0.2-19   miniUI_0.1.1.1     curl_5.0.2        \n[49] processx_3.8.1     pkgbuild_1.4.0     lattice_0.21-9     plyr_1.8.8        \n[53] withr_3.0.0        shiny_1.7.5        groupdata2_2.0.2   evaluate_0.21     \n[57] survival_3.5-7     proxy_0.4-27       RcppParallel_5.1.7 xts_0.13.1        \n[61] xml2_1.3.6         pillar_1.9.0       DT_0.28            stats4_4.3.2      \n[65] shinyjs_2.1.0      generics_0.1.3     hms_1.1.3          rstantools_2.3.1  \n[69] munsell_0.5.0      scales_1.2.1       minqa_1.2.5        gtools_3.9.4      \n[73] xtable_1.8-4       class_7.3-22       glue_1.6.2         tools_4.3.2       \n[77] shinystan_2.6.0    lme4_1.1-33        colourpicker_1.2.0 grid_4.3.2        \n[81] QuickJSR_1.1.3     crosstalk_1.2.0    colorspace_2.1-0   nlme_3.1-163      \n[85] cli_3.6.1          fansi_1.0.6        V8_4.3.0           gtable_0.3.4      \n[89] digest_0.6.33      farver_2.1.1       htmlwidgets_1.6.2  htmltools_0.5.6   \n[93] lifecycle_1.0.4    mime_0.12          gridtext_0.1.5     shinythemes_1.2.0 \n[97] MASS_7.3-60       \n```\n:::\n:::\n\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\t\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n:::\n\n::::\n\n\n::::: {.panel-tabset}\n\n\n\n:::::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}